/**
 * Reports page
 */

import { DashboardLayout } from '../layouts/DashboardLayout';

interface Report {
  id: string;
  title: string;
  generatedBy: string;
  date: string;
  type: 'clinic' | 'consultation' | 'health-trends';
}

export const Reports = () => {
  const reports: Report[] = [
    {
      id: '1',
      title: 'Monthly Clinic Report',
      generatedBy: 'Dr. Admin',
      date: '2024-01-10',
      type: 'clinic',
    },
    {
      id: '2',
      title: 'Consultation Summary - John Doe',
      generatedBy: 'Dr. Smith',
      date: '2024-01-12',
      type: 'consultation',
    },
    {
      id: '3',
      title: 'Health Trends Analysis Q4 2024',
      generatedBy: 'Analytics Team',
      date: '2024-01-05',
      type: 'health-trends',
    },
  ];

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'clinic':
        return '🏥';
      case 'consultation':
        return '👨‍⚕️';
      case 'health-trends':
        return '📈';
      default:
        return '📄';
    }
  };

  return (
    <DashboardLayout>
      <div className="p-6">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-3xl font-bold text-gray-800">Reports</h1>
          <button className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition">
            + Generate Report
          </button>
        </div>

        {/* Reports List */}
        <div className="space-y-4">
          {reports.map((report) => (
            <div key={report.id} className="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition">
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-4">
                  <span className="text-4xl">{getTypeIcon(report.type)}</span>
                  <div>
                    <h3 className="text-lg font-bold text-gray-800">{report.title}</h3>
                    <p className="text-gray-600 text-sm">
                      Generated by {report.generatedBy} on {report.date}
                    </p>
                  </div>
                </div>
                <button className="text-blue-600 hover:text-blue-700 font-semibold">
                  Download
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </DashboardLayout>
  );
};
